version: '3'

services:
  db:
    image: arm64v8/mysql
    volumes:
      - ~/src/mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: companyhub_db_testing
