name: CI

on: [ push, pull_request ]

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  NODE_ENV: "development"
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "fake"
  CLERK_SECRET_KEY: "fake"
  OPENAI_API_KEY: "fake"
  PINECONE_ENVIRONMENT: "fake"
  PINECONE_API_KEY: "fake"
  PINECONE_INDEX: "fake"
  UPSTASH_REDIS_REST_URL: "https://fake.com"
  UPSTASH_REDIS_REST_TOKEN: "fake"
  GITHUB_WEBHOOK_SECRET: "fake"
  GITHUB_WEBHOOK_LISTENER_URL: "https://fake.com"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: push prisma schema
        run: npx prisma db push --accept-data-loss

      - name: Unit Tests
        run: npm run test:ci